from typing import SupportsFloat

from aspartik.distributions import (
    Continuous,
    Sample,
    Statistics,
)
from aspartik.rng import RNG

class Beta(Continuous, Statistics, Sample[float]):
    def __init__(self, shape_a: SupportsFloat, shape_b: SupportsFloat): ...
    @property
    def shape_a(self) -> float: ...
    @property
    def shape_b(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class Exponential(Continuous, Statistics, Sample[float]):
    def __init__(self, rate: SupportsFloat): ...
    @property
    def rate(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class Gamma(Continuous, Statistics, Sample[float]):
    def __init__(self, shape: SupportsFloat, rate: SupportsFloat): ...
    @property
    def shape(self) -> float: ...
    @property
    def rate(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class InverseGamma(Continuous, Statistics, Sample[float]):
    def __init__(self, shape: SupportsFloat, rate: SupportsFloat): ...
    @property
    def shape(self) -> float: ...
    @property
    def rate(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class Laplace(Continuous, Statistics, Sample[float]):
    def __init__(self, location: SupportsFloat, scale: SupportsFloat): ...
    @property
    def location(self) -> float: ...
    @property
    def scale(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class LogNormal(Continuous, Statistics, Sample[float]):
    def __init__(self, location: SupportsFloat, scale: SupportsFloat): ...
    @property
    def location(self) -> float: ...
    @property
    def scale(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class Normal(Continuous, Statistics, Sample[float]):
    def __init__(self, mean: SupportsFloat, std_dev: SupportsFloat): ...
    @property
    def mean(self) -> float: ...
    @property
    def std(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...

class Uniform(Continuous, Statistics, Sample[float]):
    def __init__(self, min: SupportsFloat, max: SupportsFloat): ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...

    # Continuous
    def pdf(self, x: SupportsFloat) -> float: ...
    def ln_pdf(self, x: SupportsFloat) -> float: ...
    def cdf(self, x: SupportsFloat) -> float: ...
    def inverse_cdf(self, p: SupportsFloat) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    # Statistics
    def mean(self) -> float: ...
    def median(self) -> float: ...
    def mode(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def entropy(self) -> float: ...
    # Sample[float]
    def sample(self, rng: RNG) -> float: ...
